# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86e665dd26bce032f1e52b4c4ace0de473eb5503295ec52426d77cf26ec8106c775d9c27909657607e56833613f7e60da3c1f580d5b78f8eab7d930f25258a08

test:
  secret_key_base: 2da4bf220a1c3147661be40e10f0cbd1ac6d152e2e533f00f16e455c07dc93e4579594546e43d94e6e8bd90ee66bc498c87019f545c0cd4efd0c0721a39d6983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
